<?xml version="1.0" encoding="utf-8"?><Database Name="SocialNetworkPalestra" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-P4BJUM48\SQLEXPRESS02;Initial Catalog=SocialNetworkPalestra;Integrated Security=True" SettingsObjectName="FitnessLink.Properties.Settings" SettingsPropertyName="SocialNetworkPalestraConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AGGIUNTA" Member="AGGIUNTA">
    <Type Name="AGGIUNTA">
      <Column Name="NomeEsercizio" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GruppoMuscolareEsercizio" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CodiceAllenamento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ALLENAMENTO_AGGIUNTA" Member="ALLENAMENTO" ThisKey="CodiceAllenamento" OtherKey="CodiceAllenamento" Type="ALLENAMENTO" IsForeignKey="true" />
      <Association Name="ESERCIZIO_AGGIUNTA" Member="ESERCIZIO" ThisKey="NomeEsercizio,GruppoMuscolareEsercizio" OtherKey="Nome,GruppoMuscolare" Type="ESERCIZIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VISITA" Member="VISITA">
    <Type Name="VISITA">
      <Column Name="CodiceVisita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataVisita" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="OraVisita" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="PrezzoVisita" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Paziente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Medico" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Association Name="MEDICO_VISITA" Member="MEDICO1" ThisKey="Medico" OtherKey="CF" Type="MEDICO" IsForeignKey="true" />
      <Association Name="UTENTE_VISITA" Member="UTENTE" ThisKey="Paziente" OtherKey="IDutente" Type="UTENTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ALLENAMENTO" Member="ALLENAMENTO">
    <Type Name="ALLENAMENTO">
      <Column Name="CodiceAllenamento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Titolo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DataAllenamento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DurataMinuti" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LivelloIntensità" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Utente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ALLENAMENTO_AGGIUNTA" Member="AGGIUNTA" ThisKey="CodiceAllenamento" OtherKey="CodiceAllenamento" Type="AGGIUNTA" />
      <Association Name="ALLENAMENTO_POST" Member="POST" ThisKey="CodiceAllenamento" OtherKey="AllenamentoCollegato" Type="POST" />
      <Association Name="UTENTE_ALLENAMENTO" Member="UTENTE1" ThisKey="Utente" OtherKey="IDutente" Type="UTENTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AMICIZIA" Member="AMICIZIA">
    <Type Name="AMICIZIA">
      <Column Name="Richiedente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ricevente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StatoAmicizia" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="UTENTE_AMICIZIA" Member="UTENTE" ThisKey="Ricevente" OtherKey="IDutente" Type="UTENTE" IsForeignKey="true" />
      <Association Name="UTENTE_AMICIZIA1" Member="UTENTE1" ThisKey="Richiedente" OtherKey="IDutente" Type="UTENTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ESERCIZIO" Member="ESERCIZIO">
    <Type Name="ESERCIZIO">
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GruppoMuscolare" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Creatore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ESERCIZIO_AGGIUNTA" Member="AGGIUNTA" ThisKey="Nome,GruppoMuscolare" OtherKey="NomeEsercizio,GruppoMuscolareEsercizio" Type="AGGIUNTA" />
      <Association Name="UTENTE_ESERCIZIO" Member="UTENTE" ThisKey="Creatore" OtherKey="IDutente" Type="UTENTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.INTERAZIONE" Member="INTERAZIONE">
    <Type Name="INTERAZIONE">
      <Column Name="IDinterazione" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoInterazione" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Testo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Utente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="INTERAZIONE_POST" Member="POST" ThisKey="IDinterazione" OtherKey="Interazione" Type="POST" />
      <Association Name="UTENTE_INTERAZIONE" Member="UTENTE1" ThisKey="Utente" OtherKey="IDutente" Type="UTENTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MEDICO" Member="MEDICO">
    <Type Name="MEDICO">
      <Column Name="CF" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroTelefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Specializzazione" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="MEDICO_VISITA" Member="VISITA" ThisKey="CF" OtherKey="Medico" Type="VISITA" />
    </Type>
  </Table>
  <Table Name="dbo.MISURAZIONE_CORPOREA" Member="MISURAZIONE_CORPOREA">
    <Type Name="MISURAZIONE_CORPOREA">
      <Column Name="Utente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataMisurazione" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Peso" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Altezza" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CirconferenzaVita" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CirconferenzaBraccia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CirconferenzaGambe" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="UTENTE_MISURAZIONE_CORPOREA" Member="UTENTE1" ThisKey="Utente" OtherKey="IDutente" Type="UTENTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.POST" Member="POST">
    <Type Name="POST">
      <Column Name="IDpost" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Interazione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllenamentoCollegato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataPubblicazione" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Titolo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Didascalia" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Autore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ALLENAMENTO_POST" Member="ALLENAMENTO" ThisKey="AllenamentoCollegato" OtherKey="CodiceAllenamento" Type="ALLENAMENTO" IsForeignKey="true" />
      <Association Name="INTERAZIONE_POST" Member="INTERAZIONE1" ThisKey="Interazione" OtherKey="IDinterazione" Type="INTERAZIONE" IsForeignKey="true" />
      <Association Name="UTENTE_POST" Member="UTENTE" ThisKey="Autore" OtherKey="IDutente" Type="UTENTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UTENTE" Member="UTENTE">
    <Type Name="UTENTE">
      <Column Name="IDutente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DataRegistrazione" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NumeroTelefono" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="UTENTE_VISITA" Member="VISITA" ThisKey="IDutente" OtherKey="Paziente" Type="VISITA" />
      <Association Name="UTENTE_ALLENAMENTO" Member="ALLENAMENTO" ThisKey="IDutente" OtherKey="Utente" Type="ALLENAMENTO" />
      <Association Name="UTENTE_AMICIZIA" Member="AMICIZIA" ThisKey="IDutente" OtherKey="Ricevente" Type="AMICIZIA" />
      <Association Name="UTENTE_AMICIZIA1" Member="AMICIZIA1" ThisKey="IDutente" OtherKey="Richiedente" Type="AMICIZIA" />
      <Association Name="UTENTE_ESERCIZIO" Member="ESERCIZIO" ThisKey="IDutente" OtherKey="Creatore" Type="ESERCIZIO" />
      <Association Name="UTENTE_INTERAZIONE" Member="INTERAZIONE" ThisKey="IDutente" OtherKey="Utente" Type="INTERAZIONE" />
      <Association Name="UTENTE_MISURAZIONE_CORPOREA" Member="MISURAZIONE_CORPOREA" ThisKey="IDutente" OtherKey="Utente" Type="MISURAZIONE_CORPOREA" />
      <Association Name="UTENTE_POST" Member="POST" ThisKey="IDutente" OtherKey="Autore" Type="POST" />
    </Type>
  </Table>
</Database>